### ISSUE TITLE
Style Services

### ISSUE THREAD

**Issue by joelworsham** [realbig/rbm-theme#10]

**Comment by brashrebel** [comment]
Our services page right now is literally embarrassing. This isn't a knock on the design work. It is just an utterly useless page which presents lousy content in a way that makes it unappealing and confusing. We really need to revisit this page. Big time.

**Comment by brashrebel** [comment]
I need to bump this issue up. Our services page is just...so bad. We have to fix it.

**Comment by d4mation** [comment]
All the images on the Services Posts themselves seem to be broken as well 😱 

It looks like there are 15 total Posts with 5 per Page. Maybe the solution here would be to not use a standard Archive and try to condense things down? Having it all be on one Page with different Sections for different "Categories" of Services may be much easier to read through as a visitor.

We could still include excerpts and links to the Posts for the greater level of detail.

**Comment by joelworsham** [comment]
Schnykees... The broken images also have a weird url of `...com/files/...` instead of `...com/wp-content/uploads/...`. I tried manually changing that on an image, but still broke.

**Comment by d4mation** [comment]
Yeah, I have no idea what's up with those file paths. I can't find the proper files on the server either...

**Comment by brashrebel** [comment]
I honestly think we may need to have a deeper discussion about what our services page really needs. Truthfully we may not want to have a CPT anymore, at least for now. Most of the services currently listed we're not interested in actively promoting. We might just slim it down to one, single page.

Whoever feels like getting creative, if you want to brainstorm with me or as a group, I'd love to schedule that.

**Comment by BigActual** [comment]
I'm open to a discussion on 6/2 or 6/3. Both days completely open, but pick quick. Time is getting more precious as of late.

**Comment by brashrebel** [comment]
I'd say group hangout on 6/2 if everyone's up for it.
