### ISSUE TITLE
Publish Eric's staff profile

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM-Theme#23]
Get your pretty face on the site.

**Comment by brashrebel** [comment]
What's up with this homie?

**Comment by d4mation** [comment]
Started writing up a bio a couple days ago. Things have been crazy :/

I plan on finishing it up this weekend. I know it has been ages at this point. I'm sorry about that.

**Comment by joelworsham** [comment]
DO YOU EVEN WORK HERE?????

**Comment by d4mation** [comment]
I DO NOW!!!!!

![image](https://cloud.githubusercontent.com/assets/7770631/14581399/2f4cb95c-03ba-11e6-9b29-ee8f91481fa4.png)


Need to fix the grid still though. I'll work on that here in a moment.
