### ISSUE TITLE
Style staff page in grid of 4

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM-Theme#24]
Right now it is a row of three. Let's make it 2 over 2.

**Comment by joelworsham** [comment]
But then my face won't be front and center!

**Comment by d4mation** [comment]
Here it is as 2 over 2:

![image](https://cloud.githubusercontent.com/assets/7770631/14581453/c1adb674-03bb-11e6-9bf2-8f0d0f5ee395.png)

Do you think that looks too large? I put a screenshot of us all on one row in #23. 

The code automatically did that as it just counts the number of results and puts it in the classname. To get us two-per-row, I just set it to divide the number by 2. We may want to re-work its output to make it more flexible though.

Should we tweak publish dates to rearrange the Staff List?

**Comment by brashrebel** [comment]
I don't know really. I guess I'm not picky about it. Looks fine either way.

**Comment by d4mation** [comment]
Ok. It's live on the site with 2 per row right now in its current order.
