### ISSUE TITLE
Gear menu tooltips are gone

### ISSUE THREAD

**Issue by joelworsham** [realbig/RBM-Theme#27]
They seem to have disappeared over past week or so

**Comment by d4mation** [comment]
Did some crawling through the Wayback Machine to try to see what it looked like previously and I couldn't find anything&mdash;They seem to have been just icons as far back as January.

The only reference in the codebase that seems to mention tooltips for the menu is [right here](https://github.com/realbig/RBM-Theme/blob/master/includes/class-rbmtheme-walker-circularnav.php#L89), but looking at the file's history in Git it has always been commented out.

When uncommented, this happens:

![image](https://cloud.githubusercontent.com/assets/7770631/15470656/c7a742c2-20bf-11e6-95a8-6f3842cbce5b.png)

If you hover over the icons, the standard `title` attribute still shows up as is normal for `<a>` tags:

![image](https://cloud.githubusercontent.com/assets/7770631/15470707/0307e722-20c0-11e6-90d9-8617b11547cf.png)

What is the functionality here supposed to be like? I figure it was something like that first screenshot but much more polished. It just seems odd that the line has always been commented out like that according to Git. Maybe a `--force push` occurred at some point?

**Comment by joelworsham** [comment]
This is odd.... It was custom tooltips that appeared when hovering and followed the cursor. It was there up until recently. I'm thoroughly confused :|

**Comment by d4mation** [comment]
That's really weird 😕 

Do you happen to have those changes in a local branch/commit? Maybe they just never made it onto GitHub and the changes on the server got overwritten at some point.

**Comment by d4mation** [comment]
Seems to be related to #8. Haven't been able to find any related commits, unfortunately.
