### ISSUE TITLE
Add duplicate post or page capability.

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM-Theme#29]
Add a button in the list of pages, posts or custom post types so that we can duplicate posts, pages or cpts at the click of a button. 

There are plugins for this or you can hand code. No preference here. When a duplication occurs, the user should be able to modify the title and designate the URI versus having the system create something default, like /[Original_Post_Name-2].

**Comment by d4mation** [comment]
When you rename a Page/Post, if you clear out the URL it will automatically generate one based on the new Post Title for you. Is that what you're looking for? I know you mentioned renaming it before the Post/Page gets duplicated, but you'll be editing these afterwards anyway, right?

If so, activating a plugin like [Post Duplicator](https://wordpress.org/plugins/post-duplicator/) would do just fine.

![image](http://i.imgur.com/bc4fGM0.gif)

**Comment by BigActual** [comment]
I was hoping to avoid the extra, forgettable, step of clearing out the URL

**Comment by d4mation** [comment]
I'll look into this. I'm not sure if there's anything out there with that specific feature. 

Building out an interface for it if we needed to go custom shouldn't be too difficult I don't think. Basically it would delay the Duplication until the new Post Title is entered. 

Would you want it to keep the same URL as the new Post Title generated automatically, or are you wanting the URL to be entirely independent of the new Post Title? (Example: Page named "Contact Us", URL changed to "/contact")

**Comment by BigActual** [comment]
Ooh, my reply was misleading. Don't worry about the extra step. Go ahead with the Post Duplicator Plugin. Save the headache.

**Comment by d4mation** [comment]
Ah, my bad. 

Plugin activated 👍 All Posts/Pages/Custom Post Types have a `Duplicate <Post Type>` button now along side the Edit/Quick Edit/Etc. buttons.

**Comment by BigActual** [comment]
Tks
