### ISSUE TITLE
Images that are links getting green top and bottom borders on hover

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM-Theme#3]
http://rbmin.staging.wpengine.com/free-website-evaluation/
Pie charts.

**Comment by joelworsham** [comment]
Yeah... I'll probably need a more elegant solution, but for now you can go into the image settings, and give the LINK a CSS class of "no-effect"

**Comment by d4mation** [comment]
Lines 76-98 may solve that. I used the same link animations for RBP.

https://github.com/realbigplugins/theme2016/blob/8d4a1db4da2eaed657faa47b7d10da8f77d74b84/build/sass/global/_base.scss#L76

**Comment by joelworsham** [comment]
I simply removed that animation. It was proving to be very inconsistent throughout the site. It didn't work at all on links that had line breaks in them. I just made it `text-decoration: underline;`

**Comment by d4mation** [comment]
Ah, I haven't encountered that yet. That definitely would break them though.

**Comment by joelworsham** [comment]
Yeah, they weren't working **at all** on RBM anyways. Just went for the simple solution ;)
