### ISSUE TITLE
Fix this #$%^&*(*&^%$#$%^&* permalink issue once and for all

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM-Theme#33]
I'm pretty much sick of every single client and potential client telling me politely that our gosh dang website is 404ing all over the place. Hugely embarrassing and needs to never happen again.

We need to make a custom plugin, register the post types in that, activate it and turn off CPT Onomies. And we need to do it yesterday.

**Comment by joelworsham** [comment]
Mmmm my schedule for yesterday is tight, I'll see if I can squeeze it in.

**Comment by d4mation** [comment]
Just happened again. 😒

**Comment by d4mation** [comment]
This should be finally solved with the creation of the following repositories:

https://github.com/realbig/RBM-Clients-CPT
https://github.com/realbig/RBM-Evaluations-CPT
https://github.com/realbig/RBM-Features-CPT
https://github.com/realbig/RBM-Jobs-CPT
https://github.com/realbig/RBM-Services-CPT
https://github.com/realbig/RBM-Staff-CPT
