### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM-Theme#39]
Any reason we're not using SSL on RBM.com? 

If you're on RBP.com and go to check Plugin updates or something it inevitably takes you to RBM.com for the Network Admin and throws a big warning in your face about it not being secure. It is pretty annoying :/

**Comment by joelworsham** [comment]
Related to realbigplugins/theme2016#60 Definitely agree.

**Comment by brashrebel** [comment]
There's no reason to not roll with it. Not even all that hard...I think.

**Comment by d4mation** [comment]
It should just be a matter of grabbing a SSL-cert via WP Engine. Then ideally doing a search/replace on the Database to swap any references from `http://rbm.com` to `https://rbm.com`. 

However, with the size of that database, that may not be realistic :/ I had to SFTP it onto the server and have WP Engine do the import for me recently when working on a sub-site. The upload limit for phpMyAdmin is set to a mere 50MB and the import for that single sub-site was 300MB. I'd imagine the entire multisite would be much larger.

**Comment by BigActual** [comment]
@joelworsham would you take this ticket to completion this month, please?

**Comment by joelworsham** [comment]
Yes

**Comment by d4mation** [comment]
@joelworsham took care of this back on June 13th :tada:
