### ISSUE TITLE
New Navigation

### ISSUE THREAD

**Issue by d4mation** [realbig/rbm-theme#41]
The navigation we have now is very creative, but it seems to be confusing to some users. It also leads to problems like #38.

We could potentially go for something more traditional but then add elements like having it stick at the top of the screen and shrink down our logo and/or remove/rearrange things when it sticks to the top of the screen.

This could also solve #31 by standardizing the Logo a bit better. On Scroll we could have it shrink down to just the Lightbulb+Gear but when at the top of the page, show the full Logo.

Here's an example of this in action. Sorry about the low FPS recording :/ The effect is smoother outside of my crappy screen recording software.
![image](http://i.imgur.com/oDSa9IW.gif)

**Comment by joelworsham** [comment]
Yeah I'm down.

**Comment by BigActual** [comment]
Sounds good

**Comment by d4mation** [comment]
Would this be the variant of the "full size" logo we should be using?

If so, does anyone have a vector of it? I've got a vector of the Lightbulb+Gear, but nothing else. I figure having a vector for something like this eliminates possible discrepancies if I were to attempt to recreate it at the correct size and with the right font. It may allow for a more crisp logo that way as well, since rasters are known to be blurry :/

![image](https://user-images.githubusercontent.com/7770631/29577073-22b1f2a4-8738-11e7-890e-dfbdf2748fc9.png)

**Comment by joelworsham** [comment]
I don't. The whole reason I went with a "different logo" was because no one had it and I was told it'd be no problem to just make something that fit well on the website.

Now that we've changed our minds on that, we've gotta tackle getting that logo vectorized :P

**Comment by brashrebel** [comment]
I don't think there's ever been a vector. Steve has the original artwork somewhere which might help. All I have is what you have.

**Comment by BigActual** [comment]
[RBM Logo.zip](https://github.com/realbig/RBM-Theme/files/1245478/RBM.Logo.zip)

**Comment by d4mation** [comment]
@BigActual Can you export those .AI files to .SVG? For some reason I am unable to convert those.

**Comment by BigActual** [comment]
[RBM Logo.zip](https://github.com/realbig/RBM-Theme/files/1245539/RBM.Logo.zip)

**Comment by BigActual** [comment]
New SVGs in the zip file

**Comment by d4mation** [comment]
Having to update this site to the newest version of Foundation to get around some oddities in the way the project was built. In order to include the additional Foundation "plugins" we'd need for this functionality, I'd have to track down the exact match for the version that was present which would have proved very difficult.

Much easier to refactor to use an external dependency :+1:
