### ISSUE TITLE
More prominent title text for circular nav links

### ISSUE THREAD

**Issue by brashrebel** [realbig/rbm-theme#8]
Right now the text for the links in the circular nav does appear on hover but we should make that more visible. I'm envisioning something like the text instantly appearing somewhat below and to the side of the hovered on item with something like an underline coming out from the item to connect the fan to the text. Make sense? Open to other ideas but I do think this is fairly urgent.

**Comment by joelworsham** [comment]
I'm actually going back and forth on whether or not I think text is necessary. Even if someone doesn't know where a button goes, clicking it and arriving at the page seems to be a good enough answer; afterall, there's only 5 buttons (and the home page icon is fairly obvious)

**Comment by BigActual** [comment]
I like the idea an believe the line should come out in the middle of each section, as if it were coming from the center of the circle and moved straight outward, making a sharp angle and underlining the copy which would be horizontal.
