### ISSUE TITLE
Firefox SVG issue

### ISSUE THREAD

**Issue by joelworsham** [realbig/RBM-Theme#9]
I can't get the transform-origin to work on FireFox, so I had to get rid of the fancy spinning gear on the drop-down menu. I'd like to get that back and working

**Comment by joelworsham** [comment]
I hate firefox

**Comment by d4mation** [comment]
[It looks like this is supported in Firefox now.](http://caniuse.com/#search=transform-origin). It seems only Opera Mini doesn't support it now.

**Comment by joelworsham** [comment]
Ohhh! You could put that animation back in if you want. I initially had the "gear" group rotate 360deg on hiding / revealing the menu. It was pretty neat. Basically, I just couldn't get the origin to be centered cross-browser. If you could get it, that'd be sweet.

**Comment by d4mation** [comment]
Strangely, it seems to be off-center on Chrome right now, haha.

Firefox works perfectly with
```
transform: rotate(360deg);
transform-origin: 50% 50%;
```

But Chrome doesn't rotate perfectly on its origin unless I do:
```
transform: rotate(360deg);
transform-origin: 50% 55%;
```

My guess is due to the Gear being slightly oblong to accommodate the shape of the Bulb. I had to correct the shape slightly when I made the Gears for #25.

**Comment by joelworsham** [comment]
Ha oh boy. Well, if you can get it working, kudos!

**Comment by d4mation** [comment]
Well, I've got it working... mostly. For some reason I can't get the keyframes animations to work in IE 11 despite the fact that they should be supported.

I just used `-webkit-transform-origin` to specify the slightly different values for Webkit-based browsers
¯\\\_(ツ)\_/¯

I also added a reverse rotating animation for when the header closes. The changes are up on Staging if you want to check them out.

**Comment by joelworsham** [comment]
Hmmm. I would recommend using `transition` rather than an animation. The way I had it before was to set a `transition: 300ms transform;` and then simply set `transform: rotate(0deg);` on closed and `transform: rotate(360deg);` on open.

I suppose if animations work, that's cool, but I don't think that interrupts are supported for animations.

**Comment by d4mation** [comment]
Good point. I just changed it over to use Transitions rather than Animations.

**Comment by d4mation** [comment]
Changes up on Live along with #25.
